/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chulien' at '21.05.17 16:41' with Gradle 2.14.1
 *
 * @author chulien, @date 21.05.17 16:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
